//GENERATED BY go-create
package main

import (
	"log"
	"os"

	c "github.com/Seifbarouni/go-service-registry/controllers"
	d "github.com/Seifbarouni/go-service-registry/database"
	"github.com/gofiber/fiber/v2"
	"github.com/joho/godotenv"
)

func main() {
	err := godotenv.Load(".env")
	if err != nil {
		log.Fatal("Error loading .env file")
	}
	d.InitializeDB(os.Getenv("DB_CONN"))
	app := fiber.New()

	app.Get("/services/:serviceName", c.GetService)
	app.Post("/services/:serviceName", c.AddService)

	log.Fatal(app.Listen(":3000"))
}