//GENERATED BY go-create
package main

import (
	d "github.com/Seifbarouni/go-service-registry/database"
	"github.com/gofiber/fiber/v2"
)

func main() {
	d.InitializeDB()
	app := fiber.New()

	/* app.Get("/services/:serviceName", c.GetService)
	app.Post("/services/:serviceName", c.PostService) */

	app.Listen(":3000")
}