//GENERATED BY go-create
package database

import (
	"github.com/Seifbarouni/go-service-registry/models"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

var DB *gorm.DB = nil

func InitializeDB() {
	database, err := gorm.Open(postgres.Open("host=localhost port=5432 user=postgres dbname=postgres password=postgres sslmode=disable"), &gorm.Config{})
	if err != nil {
		panic(err)
	}
	if err = database.AutoMigrate(&models.Service{}); err != nil {
		panic(err)
	}
	DB = database
}
