//GENERATED BY go-create
package database

import (
	"github.com/Seifbarouni/go-service-registry/models"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

var DB *gorm.DB = nil

func InitializeDB(dsn string) {
	database, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		panic(err)
	}
	if err = database.AutoMigrate(&models.Service{}); err != nil {
		panic(err)
	}
	DB = database
}
